### ISSUE TITLE
Game::isUnderAttack does not test if the square is under attack from the king

### ISSUE THREAD

**Issue by mlockett42** [jeromevonk/chess_console#2]
In some situations this will incorrectly not award a checkmate

**Comment by jeromevonk** [comment]
![position](https://user-images.githubusercontent.com/25728134/194976173-f57f9bfc-4f64-4049-9b88-58e8bed4b22a.png)

**Comment by jeromevonk** [comment]
You were absolutely right.

Function  `Game::isUnderAttack` now_ checks if a square is [under attack by the king](https://github.com/jeromevonk/chess_console/blob/master/source/chess.cpp#L785), in every direction a king can attack.

There a test condition for this [here](https://github.com/jeromevonk/chess_console/blob/master/test/checkmates.cpp#L166).

I took me almost 5 years to look at this issue, but... better late than never :P
